// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by super_sync_codegen from an OpenAPI schema.
// dart format off
// ignore_for_file: type=lint

import 'package:super_sync/super_sync.dart';

class Todo {
  const Todo({required this.id, required this.title, required this.completed, this.tags});

  final String id;
  final String title;
  final bool completed;
  final List<String>? tags;
}

class TodoSyncAdapter implements SyncEntityAdapter<Todo> {
  @override
  String get type => 'todo';

  @override
  String idOf(Todo value) => value.id;

  @override
  Map<String, Object?> encode(Todo value) => {
        'id': value.id,
        'title': value.title,
        'completed': value.completed,
        'tags': value.tags,
      };

  @override
  Todo decode(Map<String, Object?> data) => Todo(
        id: data['id']! as String,
        title: data['title']! as String,
        completed: data['completed']! as bool,
        tags: (data['tags'] as List?)?.cast<String>(),
      );
}

class User {
  const User({required this.id, required this.name, this.age});

  final String id;
  final String name;
  final int? age;
}

class UserSyncAdapter implements SyncEntityAdapter<User> {
  @override
  String get type => 'user';

  @override
  String idOf(User value) => value.id;

  @override
  Map<String, Object?> encode(User value) => {
        'id': value.id,
        'name': value.name,
        'age': value.age,
      };

  @override
  User decode(Map<String, Object?> data) => User(
        id: data['id']! as String,
        name: data['name']! as String,
        age: data['age'] as int?,
      );
}

class Message {
  const Message({required this.id, required this.text, this.edited});

  final String id;
  final String text;
  final bool? edited;
}

class MessageSyncAdapter implements SyncEntityAdapter<Message> {
  @override
  String get type => 'message';

  @override
  String idOf(Message value) => value.id;

  @override
  Map<String, Object?> encode(Message value) => {
        'id': value.id,
        'text': value.text,
        'edited': value.edited,
      };

  @override
  Message decode(Map<String, Object?> data) => Message(
        id: data['id']! as String,
        text: data['text']! as String,
        edited: data['edited'] as bool?,
      );
}

/// Registers every generated model on [sync] in one call.
void registerSuperSyncModels(SuperSync sync) {
  sync.register(
    TodoSyncAdapter(),
    fields: const [
      SyncField.text('title'),
      SyncField.boolean('completed', indexed: true),
    ],
  );
  sync.register(
    UserSyncAdapter(),
    fields: const [
      SyncField.text('name'),
      SyncField.integer('age'),
    ],
  );
  sync.register(
    MessageSyncAdapter(),
    fields: const [
      SyncField.text('text'),
      SyncField.boolean('edited'),
    ],
  );
}

/// Builds a fully-wired [AppSync] in one call: constructs
/// SuperSync, registers every model, starts it and returns the
/// typed facade. The whole data layer in one line.
Future<AppSync> openAppSync({
  required SyncLocalStore store,
  required SyncRemote remote,
  ConflictStrategy conflictStrategy = ConflictStrategy.serverWins,
  SyncConfig config = const SyncConfig(),
  bool autoSync = true,
}) async {
  final sync = SuperSync(
    store: store,
    remote: remote,
    conflictStrategy: conflictStrategy,
    config: config,
    autoSync: autoSync,
  );
  registerSuperSyncModels(sync);
  await sync.start();
  return AppSync(sync);
}

/// A single typed entry point over every generated model.
class AppSync {
  AppSync(this.sync);

  final SuperSync sync;

  /// The live sync status (phase, pending, dead-lettered).
  Stream<SyncStatus> get status => sync.status;

  /// Runs one full sync cycle now.
  Future<void> syncNow() => sync.sync();

  /// Closes the engine and the underlying store.
  Future<void> dispose() => sync.dispose();

  SyncRepository<Todo> get todos => sync.repository<Todo>();
  SyncRepository<User> get users => sync.repository<User>();
  SyncRepository<Message> get messages => sync.repository<Message>();
}
