import 'package:yaml/yaml.dart';

/// Generates super_sync Dart source from an OpenAPI 3 document.
///
/// For every schema under `components/schemas` that has an `id` property, it
/// emits an immutable model, a [SyncEntityAdapter], a single
/// `registerSuperSyncModels(sync)` call, and an `AppSync` facade exposing a
/// typed repository per model — so an app's whole offline-first data layer is
/// one generated file.
///
/// The local database needs no generated schema: super_sync stores every model
/// in one generic JSON-backed table, so adding or changing a model never
/// migrates the DB.
String generateFromOpenApi(String source) {
  final doc = loadYaml(source);
  if (doc is! YamlMap) {
    throw const FormatException('Root of the OpenAPI document must be a map.');
  }
  final components = doc['components'];
  final schemas = components is YamlMap ? components['schemas'] : null;
  if (schemas is! YamlMap) {
    throw const FormatException('No components/schemas found in the document.');
  }

  final models = <_Model>[];
  for (final entry in schemas.entries) {
    final name = entry.key as String;
    final schema = entry.value;
    if (schema is! YamlMap) continue;
    final props = schema['properties'];
    if (props is! YamlMap) continue;
    final required = <String>{
      for (final r in (schema['required'] as YamlList? ?? const []))
        r as String,
    };
    if (!props.keys.contains('id')) continue; // need a stable identity
    models.add(
      _Model(
        className: _pascal(name),
        wireType: _snakeLower(name),
        fields: [
          for (final p in props.entries)
            _Field(
              jsonKey: p.key as String,
              dartName: _camel(p.key as String),
              type: _DartType.from(p.value as YamlMap),
              required: required.contains(p.key),
            ),
        ],
      ),
    );
  }

  if (models.isEmpty) {
    throw const FormatException(
      'No schemas with an "id" property were found to generate.',
    );
  }

  return _emit(models);
}

class _Model {
  _Model({
    required this.className,
    required this.wireType,
    required this.fields,
  });
  final String className;
  final String wireType;
  final List<_Field> fields;
}

class _Field {
  _Field({
    required this.jsonKey,
    required this.dartName,
    required this.type,
    required this.required,
  });
  final String jsonKey;
  final String dartName;
  final _DartType type;
  final bool required;

  String get nullableType => required ? type.name : '${type.name}?';
}

class _DartType {
  _DartType(this.name, {this.itemCast});
  final String name;
  final String? itemCast; // element cast for List types

  static _DartType from(YamlMap prop) {
    if (prop.containsKey(r'$ref')) return _DartType('Map<String, Object?>');
    switch (prop['type']) {
      case 'string':
        return _DartType('String');
      case 'integer':
        return _DartType('int');
      case 'number':
        return _DartType('double');
      case 'boolean':
        return _DartType('bool');
      case 'array':
        final items = prop['items'];
        final el = items is YamlMap ? _DartType.from(items).name : 'Object?';
        return _DartType('List<$el>', itemCast: el);
      default:
        return _DartType('Map<String, Object?>');
    }
  }

  bool get isList => itemCast != null;
}

String _emit(List<_Model> models) {
  final b = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by super_sync_codegen from an OpenAPI schema.')
    ..writeln('// dart format off')
    ..writeln('// ignore_for_file: type=lint')
    ..writeln()
    ..writeln("import 'package:super_sync/super_sync.dart';")
    ..writeln();

  for (final m in models) {
    _emitModel(b, m);
    _emitAdapter(b, m);
  }
  _emitRegistration(b, models);
  return b.toString();
}

void _emitModel(StringBuffer b, _Model m) {
  b
    ..writeln('class ${m.className} {')
    ..write('  const ${m.className}({');
  b.write(
    m.fields
        .map(
          (f) =>
              f.required ? 'required this.${f.dartName}' : 'this.${f.dartName}',
        )
        .join(', '),
  );
  b.writeln('});');
  b.writeln();
  for (final f in m.fields) {
    b.writeln('  final ${f.nullableType} ${f.dartName};');
  }
  b
    ..writeln('}')
    ..writeln();
}

void _emitAdapter(StringBuffer b, _Model m) {
  final cls = m.className;
  b
    ..writeln('class ${cls}SyncAdapter implements SyncEntityAdapter<$cls> {')
    ..writeln('  @override')
    ..writeln("  String get type => '${m.wireType}';")
    ..writeln()
    ..writeln('  @override')
    ..writeln('  String idOf($cls value) => value.id;')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Map<String, Object?> encode($cls value) => {');
  for (final f in m.fields) {
    b.writeln("        '${f.jsonKey}': value.${f.dartName},");
  }
  b
    ..writeln('      };')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  $cls decode(Map<String, Object?> data) => $cls(');
  for (final f in m.fields) {
    b.writeln('        ${f.dartName}: ${_decodeExpr(f)},');
  }
  b
    ..writeln('      );')
    ..writeln('}')
    ..writeln();
}

String _decodeExpr(_Field f) {
  final access = "data['${f.jsonKey}']";
  if (f.type.isList) {
    final cast = f.type.itemCast;
    return f.required
        ? '($access! as List).cast<$cast>()'
        : '($access as List?)?.cast<$cast>()';
  }
  return f.required
      ? '$access! as ${f.type.name}'
      : '$access as ${f.type.name}?';
}

void _emitRegistration(StringBuffer b, List<_Model> models) {
  b
    ..writeln('/// Registers every generated model on [sync] in one call.')
    ..writeln('void registerSuperSyncModels(SuperSync sync) {');
  for (final m in models) {
    b.writeln('  sync.register(${m.className}SyncAdapter());');
  }
  b
    ..writeln('}')
    ..writeln();

  // One-call setup: build + register + start, return the typed facade.
  b
    ..writeln('/// Builds a fully-wired [AppSync] in one call: constructs')
    ..writeln('/// SuperSync, registers every model, starts it and returns the')
    ..writeln('/// typed facade. The whole data layer in one line.')
    ..writeln('Future<AppSync> openAppSync({')
    ..writeln('  required SyncLocalStore store,')
    ..writeln('  required SyncRemote remote,')
    ..writeln(
      '  ConflictStrategy conflictStrategy = ConflictStrategy.serverWins,',
    )
    ..writeln('  SyncConfig config = const SyncConfig(),')
    ..writeln('  bool autoSync = true,')
    ..writeln('}) async {')
    ..writeln('  final sync = SuperSync(')
    ..writeln('    store: store,')
    ..writeln('    remote: remote,')
    ..writeln('    conflictStrategy: conflictStrategy,')
    ..writeln('    config: config,')
    ..writeln('    autoSync: autoSync,')
    ..writeln('  );')
    ..writeln('  registerSuperSyncModels(sync);')
    ..writeln('  await sync.start();')
    ..writeln('  return AppSync(sync);')
    ..writeln('}')
    ..writeln();

  b
    ..writeln('/// A single typed entry point over every generated model.')
    ..writeln('class AppSync {')
    ..writeln('  AppSync(this.sync);')
    ..writeln()
    ..writeln('  final SuperSync sync;')
    ..writeln()
    ..writeln('  /// The live sync status (phase, pending, dead-lettered).')
    ..writeln('  Stream<SyncStatus> get status => sync.status;')
    ..writeln()
    ..writeln('  /// Runs one full sync cycle now.')
    ..writeln('  Future<void> syncNow() => sync.sync();')
    ..writeln()
    ..writeln('  /// Closes the engine and the underlying store.')
    ..writeln('  Future<void> dispose() => sync.dispose();')
    ..writeln();
  for (final m in models) {
    final getter = _camel(_plural(m.wireType));
    b.writeln(
      '  SyncRepository<${m.className}> get $getter => '
      'sync.repository<${m.className}>();',
    );
  }
  b.writeln('}');
}

// --- naming helpers ---------------------------------------------------------

List<String> _words(String s) =>
    s.split(RegExp(r'[_\- ]+')).where((w) => w.isNotEmpty).toList();

String _camel(String s) {
  final w = _words(s);
  if (w.isEmpty) return s;
  return w.first.toLowerCase() +
      w.skip(1).map((x) => x[0].toUpperCase() + x.substring(1)).join();
}

String _pascal(String s) {
  final c = _camel(s);
  return c.isEmpty ? c : c[0].toUpperCase() + c.substring(1);
}

String _snakeLower(String s) => _words(s).map((w) => w.toLowerCase()).join('_');

String _plural(String s) {
  if (s.endsWith('y')) return '${s.substring(0, s.length - 1)}ies';
  if (s.endsWith('s')) return s;
  return '${s}s';
}
